[package]
name = "DemoForLibsodium"
version = "0.1.0"
authors = ["v <valbendan@hotmail>"]
edition = "2018"
build   = "build.rs"

[[bin]]
name = "demo"
path = "src/main.rs"


[build-dependencies]
vcpkg = "0.2"

